### ISSUE TITLE
Do not display Notch for external monitors

### ISSUE THREAD

**Issue by stcheng** [megabitsenmzq/Notch-Simulator#6]
And only display the notch in the native monitor.

**Comment by megabitsenmzq** [comment]
Did you try to run the app after connecting the monitor? If you run it before connecting the monitor, the current version will have some problems.

**Comment by notsidney** [comment]
I have the same issue, I already had my external monitor connected and when I ran the app, it also showed on the external, even after restarting the app.

**Comment by megabitsenmzq** [comment]
Can you guys show me your monitor arrangement in the system preference? That might be helpful.
Like this: 
![screenshro1](https://tva1.sinaimg.cn/large/008i3skNgy1gvmtiz70mrj61260u0jtm02.jpg)

And the right behavior should looks like this: 
![screenshro2](https://tva1.sinaimg.cn/large/008i3skNgy1gvmtjxize5j61400u0n3o02.jpg)
